### ISSUE TITLE
[Question] Root password?

### ISSUE THREAD

**Issue by Suleman-Elahi** [abcdesktopio/abcdesktopio#1]
I was trying to the web shell. What is the default root password?

**Comment by alexandredevely** [comment]
The default root password is lmdpocpetit

You can read or change it in the Dockerfile https://github.com/abcdesktopio/oc.user/blob/main/Dockerfile 
Line 150

# create an ubuntu user
RUN echo "balloon:lmdpocpetit" | chpasswd $BUSER
